sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VqGjNZEbKLSNgTMzZ86syL0pWiTnqjxO1gQ5XqRP+T10ne5h3K7f8Kh+rmxrPfvRlkuJVXMKyeZY8Gkw5hKmd855cyu+Bl3z/Nlt0/ey5vhAybh4jgOBIxCLoliNntRBY24zp7F4xHpGc7qDy64PDLeDbDLytWbdhYWdkiCnnNSO6lasKldC8zDXf/O9gHhPrWv4m0u4ciur5rtw8hIY4qFbD4U9bVUI4EqNB2YCASbGN/7jVniEtQf+0pQ5IIjtLJomRfC3mKNm7MSiWtsGJVHNG9OLKMVfGT/DrXhuO0p/cNwWdZWtVAgBMmrZJ17JD8QbvpU5OEe+IkD94IZ0tCNOtHmo+sdx2ZIB0S0qwGg2WU8V3XkhxJ5I8w4jyq+P2hA8m+qAbKWEtBPEhWiQUui0BHj4Yw5b5ERHzNqCycKbuqruuQ2c7BufftVxgXYt3Hqn6/izB7FHZg4rW5IUgiLGVy8FEmzukNVmZyhIMjOPM5tVF4J6BfcJYD6NAsWJvpdqweKbtx/IUCrSwaoHxBAhq71vQm0D45EKN91gQeDAE5M+2JqRbM4f+bGZVWY/7lMIoiF0+2LURgvS0pfrcAritknvyAzneOcPBHXbUZM1TuIvUnIRe1akLrUfSjtw1oamo3LuMYSKRvpMOd4OlMuWtVu7e/4Ip5DQBCpkAX0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Theologico-Political-Treatise-Part-4_992
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy